[versions]
kotlin = "2.1.0"
androidx-core = "1.15.0"
androidx-appcompat = "1.7.0"
androidx-compose = "1.7.8"
androidx-navigation = "2.8.9"
androidx-lifecycle = "2.8.7"
androidx-room = "2.6.1"
com-google-material = "1.12.0"
com-google-firebase = "22.3.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
com-google-material = { module = "com.google.android.material:material", version.ref = "com-google-material" }
com-google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "com-google-firebase" }
com-google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "com-google-firebase" }
